# action.yml
name: 'PanIndex-build-action'
author: 'libsgh <woiyyng@gmail.com>'
description: 'Build PanIndex binaries'
runs:
  using: "composite"
  steps:
    - run: |
        "${GITHUB_WORKSPACE}/.github/build.sh"
      shell: bash
branding:
  icon: 'package'
  color: 'blue'
